title: Chitranshi Singh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <body>

  <b>Data Analyst</b> <br>
  Berlin, Germany <br> <br>


  <!-- Trigger/Open The Modal -->
  <button id="myBtn">About me</button>

  <!-- The Modal -->
  <div id="myModal" class="modal">

     <!-- Modal content -->
     <div class="modal-content">
         <span class="close">&times;</span>
         <p>With a background in Auditing and Reporting in Cybersecurity, I specialize in cleaning and handling large
             amounts of data, producing insightful reports with strong attention to detail, and presenting them to
             stakeholders. Having worked with data throughout my career, my transition to a full-time Data Analyst felt
             like a natural choice.</p>

         <p>
             Driven by a genuine curiosity and a knack for problem-solving, I enjoy tackling complex problems and turning
             challenges into opportunities. I am keen about bridging the gap between numbers and real-world implications
             for the business and bringing value to an organization. Being a confident presenter and an effective
             collaborator, I have the ability to present complex insights in an accessible and user-friendly way.</p>

         <p>
             I’m passionate to use my expertise to analyze larger data sets and draw insights that can guide business
             decisions and lead to success.</p>

          Tools:
         <li> SQL </li>
         <li> Excel </li>
         <li> Tableau </li>
         <li> Python </li>

     </div>
  </div>

  <br><br>
  <a href="https://chitranshi-singh.github.io/Chitranshi_Singh_Resume.pdf">Resume </a> <br>
  <a href="https://www.linkedin.com/in/chitranshi-singh-7848b0245">LinkedIn Profile </a> <br>
  <a href="https://github.com/chitranshi-singh">GitHub Repository </a> <br>
  <a href="https://public.tableau.com/app/profile/chitranshi3388">Tableau Public </a> <br>

  <br>

  <a href="mailto:chitranshi14singh@gmail.com">Contact me</a> <br>


  <script>
     // Get the modal
     var modal = document.getElementById("myModal");

     // Get the button that opens the modal
     var btn = document.getElementById("myBtn");

     // Get the <span> element that closes the modal
     var span = document.getElementsByClassName("close")[0];

     // When the user clicks the button, open the modal
     btn.onclick = function () {
         modal.style.display = "block";
     }

     // When the user clicks on <span> (x), close the modal
     span.onclick = function () {
         modal.style.display = "none";
     }

     // When the user clicks anywhere outside of the modal, close it
     window.onclick = function (event) {
         if (event.target == modal) {
             modal.style.display = "none";
         }
     }
  </script>

  </body>

  <style>
     /* The Modal (background) */
     .modal {
         display: none; /* Hidden by default */
         position: fixed; /* Stay in place */
         z-index: 1; /* Sit on top */
         left: 0%;
         top: 0;
         width: 100%; /* Full width */
         height: 100%; /* Full height */
         overflow: auto; /* Enable scroll if needed */
         background-color: rgb(0, 0, 0); /* Fallback color */
         background-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */
     }

     /* Modal Content/Box */
     .modal-content {
         background-color: #fefefe;
         margin: 15% auto; /* 15% from the top and centered */
         padding: 20px;
         border: 1px solid #888;
         width: 40%; /* Could be more or less, depending on screen size */
     }

     /* The Close Button */
     .close {
         color: #aaa;
         float: right;
         font-size: 28px;
         font-weight: bold;
     }

     .close:hover,
     .close:focus {
         color: black;
         text-decoration: none;
         cursor: pointer;
     }
  </style>


remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
